### ISSUE TITLE
Add ViaLegacy for support for almost every version

### ISSUE THREAD

**Issue by mrrpmrreeoow** [FlorianMichael/ViaLoadingBase#2]
ViaLegacy allows to join servers from version  classic 0.0.15 to 1.7.10
I dont know if it is implemented, but probably not. (It requires Viaversion and ViaBackwards to work)
It should work fine, because it is "ViaVersion addon"
Here is ViaLegacy repo: [https://github.com/RaphiMC/ViaLegacy](https://github.com/RaphiMC/ViaLegacy)

**Comment by mrrpmrreeoow** [comment]
It looks like it is already here

**Comment by mrrpmrreeoow** [comment]
Old protocols are in version list, but vialegacy is not in build.gradle

**Comment by florianreuth** [comment]
i have my own vialegacy and i don't want to break my code base for my private projects, i won't add it

**Comment by mrrpmrreeoow** [comment]
> i have my own vialegacy and i don't want to break my code base for my private projects, i won't add it

Will be version with your ViaLegacy ever published to public?

**Comment by florianreuth** [comment]
no, if you want ViaLegacy, you can implement it at your own, maybe i will make a implementation in ViaForge, but in generally, i don't want it in ViaLoadingBase since i have my own codebase for legacy versions
